services:
  database:
    image: postgres
    container_name: delivery
    restart: "no"
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=delivey_db
    volumes:
      - pgdata:/data/postgres
volumes:
  pgdata:
    driver: local
